site_name: Python Project # TODO change this to your project name
docs_dir: docs
copyright: Copyright &copy; 2023 Paul-B98 # TODO change this to your name

nav:
  - Getting Started:
      - Package Overview: "getting_started/overview.md"
      - Installation: "getting_started/installation.md"
      - Basic Usage: "getting_started/basic_usage.md"
      - Contributing: "getting_started/contributing.md"
  # - User Guide:
  - Architecture:
      - Introduction and Goals: "arc/introduction.md"
      - Architecture Constraints: "arc/constraints.md"
      - Context and Scope: "arc/context.md"
      - Solution Strategy: "arc/strategy.md"
      - Building Block View: "arc/building_block.md"
      - Runtime View: "arc/runtime.md"
      - Deployment view: "arc/deployment.md"
      - Crosscutting Concepts: "arc/concepts.md"
      - Architecture Decisions: "arc/decisions.md"
      - Quality Requirements: "arc/quality.md"
      - Risks and Technical Debt: "arc/risks.md"
      - Glossary: "arc/glossary.md"
  - API Reference: reference/

theme:
  name: material
  repo_url: "https://github.com/Paul-B98/python-project-template"
  features:
    - navigation.tabs
    - navigation.footer

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Paul-B98/python-project-template
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ # TODO change this to your project name

extra_css:
  - assets/css/code_select.css
  - assets/css/fonts.css

# Plugins and Extensions
markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.extra
  - footnotes
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search:
  - macros:
      include_dir: ./
  - gen-files:
      scripts:
        - docs/scripts/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: ["project_name"]
          options:
            docstring_style: numpy
